version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - "80:80"

    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD

  proxy:
    image: nginx:latest
    volumes:
      - ./templates:/etc/nginx/templates
      - ./conf/certpath.txt:/etc/nginx/certpath.txt
      - /etc/letsencrypt:/etc/nginx/letsencrypt
    
    restart: always
    ports:
     - 80:80
     - 443:443
    env_file:
      - ./conf/conf.env
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    name: my_network